### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by stphnlyd** [P403n1x87/austin-vscode#13]
At our workspace we would like to try this extension, but there is a policy issue that it does not have a license in the package https://marketplace.visualstudio.com/items?itemName=p403n1x87.austin-vscode

If you compare it to other extensions you see they have a license, like Microsoft's one https://marketplace.visualstudio.com/items?itemName=ms-python.python

**Comment by P403n1x87** [comment]
This should be fixed now.
