### ISSUE TITLE
flame graph does not show

### ISSUE THREAD

**Issue by stphnlyd** [P403n1x87/austin-vscode#15]
It only shows the Austin icon on the flame graph tab. This is not the same issue as #11 . I got #11 on my home PC, but on my workplace PC it does not show flame graph at all. Not sure if it relates to the fact that we use VSCode remote at work..

**Comment by stphnlyd** [comment]
I just tried remote at home PC and it's good. So it's my workplace environment that is different. I am doing profiling not opening a austin-saved file, I will try that at my workplace PC.

**Comment by stphnlyd** [comment]
@P403n1x87 could you please cut a new release of this extension to the marketplace? At our workplace it's better to officially get vscode extension from there than I making a build myself.

**Comment by P403n1x87** [comment]
@stphnlyd I will do one now. I was trying to get some other fixes in but it's taking me some time so I'll push a new patch release for now!

**Comment by P403n1x87** [comment]
@stphnlyd The fix is included in 0.9.3 but 0.10.0 should soon be available!
