### ISSUE TITLE
Task doesn't start in correct working directory

### ISSUE THREAD

**Issue by othi** [P403n1x87/austin-vscode#19]
I have a workspace with many different folders.

The task always starts in the first folder in the workspace, instead of the one with the project where the task is configured, rendering this extension impossible to use in any but the first project in the workspace.

I suspect this line is to blame:

https://github.com/P403n1x87/austin-vscode/blob/7a0eab5d439bd56c43a73ca6fef62f4fe5bb99ae/src/providers/executor.ts#L42

**Comment by P403n1x87** [comment]
👋 @othi thanks for reporting this and apologies for the suboptimal user experience. Indeed you are correct, currently the first open folder is used as working directory. I understand you would like the task to run from within the directory it is defined on. I'll see if it is possible to retrieve that URI and use that instead.

**Comment by P403n1x87** [comment]
@othi I have for the moment worked around this by showing a quick-pick dialog with the list of all the current roots. This gives at least a way to pick the right working directory for the tasks. Once the VC Code API around tasks gets extended I will provide better support for multi-root workspaces. I hope this works for you for now 🙏 .

**Comment by othi** [comment]
Works for me, thanks!
