### ISSUE TITLE
Fails to launch and closes window

### ISSUE THREAD

**Issue by tonybaloney** [P403n1x87/austin-vscode#2]
When I try and run "Profile with Austin", it opens a terminal, runs a command and then closes the terminal again.

The task failed with "Austin terminated with code 33"

but because the terminal is closed, I can't see what the error message was.

**Comment by P403n1x87** [comment]
Unfortunately, I don't seem to be able to reproduce the problem with the latest version of the extension and Austin 3. This is the code that is responsible for running the currently open Python script in a terminal and visualising the result:

https://github.com/P403n1x87/austin-vscode/blob/45dd39205d12903150ed58da6d202a3cc9f75b14/src/controller.ts#L27-L47

The command that gets sent to the terminal has the following structure

~~~
${austinPath} -i ${austinInterval} -o ${outputFile} ${sleepless} ${interpreter} ${currentUri.fsPath}
~~~

so normally this would translate into something like

~~~
austin -i 100 -o c:\Users\Gabriele\Projects\austin\test\.austin-vscode  C:\Users\Gabriele\scoop\shims\python.exe c:\Users\Gabriele\Projects\austin\test\sleepy.py
~~~

Here is what I get when I press <kbd>Shift</kbd> + <kbd>F5</kbd> on the `sleepy.py` script

![profile-with-austin-demo](https://user-images.githubusercontent.com/20231758/129790120-1d67115a-9e6d-402a-920f-98bd23d43d89.gif)

Could you try to run the command directly from e.g. PowerShell to see what the error is?

**~~PRO-TIP~~HACK** If you're quick enough you can press <kbd>Ctrl</kbd> + <kbd>C</kbd> in the terminal that pops up to grab the actual command that's being run 🙂 .

**Comment by tonybaloney** [comment]
```
austin -i 100 -o /Users/anthonyshaw/projects/austin-testing/.austin-vscode  /usr/local/bin/python3.10 /Users/anthonyshaw/projects/austin-testing/main.py
              _   _      
 __ _ _  _ __| |_(_)_ _  
/ _` | || (_-<  _| | ' \ 
\__,_|\_,_/__/\__|_|_||_| 3.0.0

🔒 Insufficient permissions. Austin requires the use of sudo on Mac OS in order
to read the memory of even its child processes. Furthermore, the System 
Integrity Protection prevents Austin from working with Python binaries
installed in certain areas of the file system. See

    🌐 https://github.com/P403n1x87/austin#compatibility

for more details.
```

**Comment by P403n1x87** [comment]
@tonybaloney I think this issue can be closed now?
