### ISSUE TITLE
command not recognized when using conda environment in Windows

### ISSUE THREAD

**Issue by sgbaird** [P403n1x87/austin-vscode#20]
I can't install `austin` via `conda` because there's no Windows package. It doesn't look like it's on PyPI either (for Windows at least), and using the Windows MSI or Chocolately doesn't automatically add `austin` to the path. The docs mention that you can specify the absolute path to `austin` using the extension settings, but there are "No Settings Found". After installing `austin`, in Windows Terminal it recognizes `austin -h` just fine.

Any suggestions?

**Comment by sgbaird** [comment]
Rolled back to `v.9.1.0` and the extension setting to specify absolute path to `austin` is available now.

**Comment by P403n1x87** [comment]
@sgbaird thanks for reporting this. I'm a bit puzzled by

> After installing austin, in Windows Terminal it recognizes austin -h just fine.

This seems to imply that `austin` actually is on the `PATH`? If you have installed Austin from either the MSI or Chocolatey, may I ask you to double-check that it was actually added to the `PATH`. This should be the default behaviour. It might be that your console session needed to be restarted for the changes to take effect after the installation.

Regarding the issue with the VS Code settings for Austin, I don't seem to be able to reproduce it. Perhaps this also requires a reload of VS Code after the installation of the extension. Would you be able to confirm this for me by re-installing the latest release of the extension, please?

**Comment by sgbaird** [comment]
Reinstalled the latest version of the extension while a fresh `conda` environment was activatated using `choco install austin`. Not sure if it mattered that the `conda` environment was active. Note that in order to upgrade I had to uninstall the MSI installed program via Windows add or remove programs. i.e. couldn't just use `choco install austin --force` or similar. Either way, it's working for me now.
