### ISSUE TITLE
austin process exited with code 127

### ISSUE THREAD

**Issue by cyraid** [P403n1x87/austin-vscode#21]
Using this task in tasks.json:
```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "austin",
      "file": "main",
      "label": "Profile Main"
    }
  ]
}
```

-----------------------------------
It gives me the error:

```
Starting Profiler in /home/user/src
Running 'austin' with args '-i 100 --pipe  /usr/bin/python3 /home/user/src/main'.
austin process exited with code 127
The terminal process failed to launch (exit code: 127)
```

**Austin version:** austin 3.1.0

-----------------------------------

It works when I run the file manually (as it shows in the errors, with --pipe and -i 100).

**Comment by cyraid** [comment]
I tried using the load file method, but it won't work (I'm using ssh remote development). It lets me pick file but then does nothing after.

```
TypeError: Cannot read property 'asWebviewUri' of undefined
	at FlameGraphViewProvider.showLoading (vscode-file://vscode-app/home/user/.vscode-server/extensions/p403n1x87.austin-vscode-0.10.2/out/providers/flamegraph.js:126)
	at vscode-file://vscode-app/home/user/.vscode-server/extensions/p403n1x87.austin-vscode-0.10.2/out/extension.js:23
	at vscode-file://vscode-app/home/user/.vscode-server/extensions/p403n1x87.austin-vscode-0.10.2/out/model.js:201
	at Array.forEach (<anonymous>)
	at AustinStats.readFromStream (vscode-file://vscode-app/home/user/.vscode-server/extensions/p403n1x87.austin-vscode-0.10.2/out/model.js:201)
	at AustinStats.readFromFile (vscode-file://vscode-app/home/user/.vscode-server/extensions/p403n1x87.austin-vscode-0.10.2/out/model.js:209)
	at vscode-file://vscode-app/home/user/.vscode-server/extensions/p403n1x87.austin-vscode-0.10.2/out/controller.js:54
```

**Comment by P403n1x87** [comment]
@cyraid thanks for reporting this. Regarding the load command, I wonder if this is just an instance of #11. Could you see if the steps described there help, please?

As for the first issue, there might be some more details as to why this is failing in the Output panel, under the Austin channel:

![Screenshot from 2021-12-08 22-33-54](https://user-images.githubusercontent.com/20231758/145302104-a91dc5d7-5f2d-410e-b9ba-1631eaacc502.png)

If so, could you please share the content of the panel?

**Comment by cyraid** [comment]
Yeah it worked when I clicked on Flame Graph, real quick, hoping I don't have to go through creating a new ticket but:
I use the Shift+F5 feature and it pastes the file twice?

```
Running 'austin' with args '-i 100 --pipe -s /usr/bin/python3 /home/user/src/home/user/src/main'
```

**Comment by P403n1x87** [comment]
This is a regression in the latest version which I'll try to get fixed asap 🙁 . Meanwhile, downgrading to 0.10.0 should bring the functionality back.

**Comment by cyraid** [comment]
> This is a regression in the latest version which I'll try to get fixed asap 🙁 . Meanwhile, downgrading to 0.10.0 should bring the functionality back.

No worries, thank you for fixing!
