### ISSUE TITLE
Trying to run pytest using Austin in VS code.

### ISSUE THREAD

**Issue by hrshdhgd** [P403n1x87/austin-vscode#24]
This may be similar to https://github.com/P403n1x87/austin-vscode/issues/21 but I'm not sure. I read the documentation at the [VS code marketplace here](https://marketplace.visualstudio.com/items?itemName=p403n1x87.austin-vscode)

Here's my situation: 
I have python project that I'm trying to profile using Austin within VS code. I'm using a MacBook (macOS Big Sur). Here's my `tasks.json`
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "austin",
            "label": "Profile tests",
            "args": [
                "python",
                "-m",
                "pytest",
            ],
            "problemMatcher": []
        }
    ]
}
```

I'm just trying to run `pytest` over the project. I'm also running this within a `conda` virtual environment. I get the following error:

```
> Executing task: Profile tests <

Starting Profiler in xxx/yyy/zzz/project-name.
Running 'austin' with args '-i 100 --pipe  python -m pytest'.
austin process exited with code 127
The terminal process failed to launch (exit code: 127).

Terminal will be reused by tasks, press any key to close it.
```

Any guidance/suggestion would be great appreciated.

**Comment by P403n1x87** [comment]
I think this might be due to the fact that `austin` is running without `sudo`. On MacOS the use of `sudo` is unfortunately mandatory (unless you have SIP disabled). One possible solution is to allow `austin` to run without password, by adding a rule in the `sudoers` file, and then actually running `sudo`, e.g.
~~~ json
        {
            "type": "austin",
            "label": "Profile tests",
            "command": ["sudo"].
            "args": [
                "python",
                "-m",
                "pytest",
            ]
        },
~~~

**Comment by P403n1x87** [comment]
@hrshdhgd thanks for trying that. I think this is now the same as #23, which I haven't been able to figure out yet 🙁 .

**Comment by hrshdhgd** [comment]
Not a problem , please let me know when you figure it out. In the meanwhile, would you know which Austin VSCode extension version and Austin version combination has proven to work in unison in the past?

**Comment by hrshdhgd** [comment]
same error.

**Comment by P403n1x87** [comment]
> Could you direct me to an example please?

You can run the same command that VS Code is trying to run from a terminal, e.g.

~~~ console
sudo austin -i 100 -o /path/to/austin/output.austin python -m pytest
~~~

and then open the `/path/to/austin/output.austin' from VS Code by clicking the OPEN button in the Flame Graph panel (or using the Cmd + Shift + A shortcut). This is equivalent to running the task.

**Comment by hrshdhgd** [comment]
Thank you so much @P403n1x87 ! That works as expected!
