### ISSUE TITLE
Respect active environment

### ISSUE THREAD

**Issue by cwerner** [P403n1x87/austin-vscode#38]
Hi :wave:

I'm not sure if I have my setup wrong - but it seems when I try to invoke `austin` as a `task` it is not using the python version/ venv selected in VSCode.
Is this expected? 
I currently specify the full path to python interpreter as my first arg.

Cheers

**Comment by P403n1x87** [comment]
@cwerner I'm afraid this is expected for tasks and you already did the right thing to work around it. However it would make sense to detect the active venv and use that, as done by the "Profile with Austin" command. I'll look into it!
