### ISSUE TITLE
Bug: Austin fails on pshell when executable path is a string

### ISSUE THREAD

**Issue by LiquidPulsar** [P403n1x87/austin-vscode#40]
Austin task fails to run (on Windows 10, powershell) if the python executable path needs to be enquoted (as there's a space in the path).
Example:
```
Starting Profiler in c:\Users\Alexandre Nole\Desktop\PyDis.
Running 'austin' with args '-i 100 --pipe  "C:\Users\Alexandre Nole\AppData\Local\Programs\Python\Python310\python.exe" "c:\Users\Alexandre Nole\Desktop\PyDis\AOC\Day24\tmp.py"'.
austin process exited with code 33

 *  The terminal process failed to launch (exit code: 33).
```
Potentially fix this by adding an option in the extension settings to specify an alias for the python executable path, eg `py`?
Alternatively, change enquoting method such that it enquotes the exact directory name with the space:
```pshell
C:\Users\"Alexandre Nole"\AppData\Local\Programs\Python\Python310\python.exe
```
The full string version works fine on cmd, but not pshell, so forcing vscode to use cmd instead is another workaround.

**Comment by P403n1x87** [comment]
0.12.0 is published with a fix for this
