### ISSUE TITLE
Add MacOS instructions for modifying `sudoers`

### ISSUE THREAD

**Issue by bgyarfas** [P403n1x87/austin-vscode#41]
It could be helpful for MacOS users if there was a note about needing to adjust the sudoers file by using `sudo visudo` and adding the following line:
```
<USER>        ALL = (root) NOPASSWD: <PATH_TO_AUSTIN>
```
(With the appropriate substitutions).

Thanks for the great work!

**Comment by P403n1x87** [comment]
@bgyarfas thanks for the feedback. I'll add more instructions in future releases of the extension, but feel free to contribute as well! 🙂
