### ISSUE TITLE
Space in path problem

### ISSUE THREAD

**Issue by francescobodria** [P403n1x87/austin-vscode#42]
I have a problem when launching a new profile with shift + F5.
The output is:
austin process exited with code 33.
and by looking at the logs in output it says:
C:\Users\Name Surname\.conda\envs\env_name\python.exe: can't open file 'c:\Users\Name': [Errno 2] No such file or directory
unfortunately I have a space in my path and I think this is what is causing the problem.
If i launch the same command:
austin -i 100 ... 
from powershell it works, then I save it into a file and I load it using the vscode palette.

**Comment by P403n1x87** [comment]
Hi @francescobodria. What version of the extension are you using? This should have been fixed in 0.10 by now https://github.com/P403n1x87/austin-vscode/commit/bd4bb1a8ef64f6d7d4d12fde5663bb439795caa4. If you're on the latest version, can you possibly share the whole output, please? 🙏

**Comment by francescobodria** [comment]
Hi, I'm using version 0.13.1

Here is the logs:

I open the command palette, and i click on profile with Austin.

It opens up a terminal window that says:
 *  Executing task: austin: profile c:\Users\Francesco Bodria\code\MapServer\fd.mindicity.ds.mapserver\src\models\ServerTimRisk.py 

Starting Profiler in c:\Users\Francesco Bodria\code\MapServer.
Running 'austin' with args '-i 100 --pipe "C:\Users\Francesco Bodria\.conda\envs\fd_mapserver\python.exe" "c:\Users\Francesco Bodria\code\MapServer\fd.mindicity.ds.mapserver\src\models\ServerTimRisk.py"'.
austin process exited with code 33

 *  The terminal process failed to launch (exit code: 33). 
 *  Terminal will be reused by tasks, press any key to close it. 

If I check the logs of vscode:
C:\Users\Francesco Bodria\.conda\envs\fd_mapserver\python.exe: can't open file 'c:\Users\Francesco': [Errno 2] No such file or directory

If I launch the command form powershell: 
austin -i 100 --pipe 'C:/Users/Francesco Bodria/.conda/envs/fd_mapserver/python.exe' 'c:/Users/Francesco Bodria/code/MapServer/fd.mindicity.ds.mapserver/src/models/ServerTimRisk.py' > './profile_timrisk.austin'
It works

**Comment by P403n1x87** [comment]
@francescobodria thanks for the extra details. The arguments seem to be quoted
~~~
Running 'austin' with args '-i 100 --pipe "C:\Users\Francesco Bodria.conda\envs\fd_mapserver\python.exe" "c:\Users\Francesco Bodria\code\MapServer\fd.mindicity.ds.mapserver\src\models\ServerTimRisk.py"'.
austin process exited with code 33
~~~
however, when the script path is passed to the interpreter, it's as if it is not quoted 🤔 . I wonder if this only happens with powershell. I'll try to reproduce this on Windows when I can.
