### ISSUE TITLE
austin: unrecognized option '--pipe'

### ISSUE THREAD

**Issue by schodge** [P403n1x87/austin-vscode#45]
Hello,

I've set up my task:

```{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "austin",
            "file": "dragonfly.py",
            "args": ["--document-id", "f9f2b069-947c-4fbf-95dc-520a663c5124"],
            "label": "Profile dragonfly",
        }
    ]
}```

but I get 

```
 *  Executing task: Profile dragonfly 

Starting Profiler in /workspaces/tome-core.
Running 'austin' with args '-i 100 --pipe /home/vscode/.pyenv/versions/document/bin/python3 /workspaces/tome-core/dragonfly.py --document-id f9f2b069-947c-4fbf-95dc-520a663c5124'.
austin process exited with code 64
```

and if I try running that directly on the terminal:

```austin -i 100 --pipe /home/vscode/.pyenv/versions/document/bin/python3 /workspaces/tome-core/dragon
fly.py --document-id f9f2b069-947c-4fbf-95dc-520a663c5124  
austin: unrecognized option '--pipe'
Try `austin --help' or `austin --usage' for more information.```

? Thanks!

**Comment by P403n1x87** [comment]
Hi there. I suspect you are using an old version of Austin. The pipe option was added in 3.0.0. Could you check that with `austin -V` and upgrade if necessary? Note that Austin is also available from PyPI and can be installed with `pip install austin-dist`.
