### ISSUE TITLE
austin process exited with code -4058

### ISSUE THREAD

**Issue by dbookstaber** [P403n1x87/austin-vscode#47]
I just installed Austin v0.13.1 in VSCode v1.82.2.  When I press Shift-F5 I get the following terminal output:

```
Executing task: austin: profile f:\VSCode\test.py 

Starting Profiler in f:\VSCode.
Running 'austin' with args '-i 100 --pipe C:\Users\...\Python310\python.exe f:\VSCode\test.py'.
spawn austin ENOENTaustin process exited with code -4058

The terminal process failed to launch (exit code: -4058).
```

**Comment by P403n1x87** [comment]
Hi @dbookstaber. Have you installed the Austin binary as well? If not you can find the instructions [here](https://github.com/P403n1x87/austin#installation).

**Comment by dbookstaber** [comment]
Ah ha!  That fixed it.  Thank you!
