### ISSUE TITLE
Line heat color can make lines unreadable on dark themes

### ISSUE THREAD

**Issue by iburakov** [P403n1x87/austin-vscode#56]
Hi! Great tools, thanks. I seem to have stumbled upon a minor problem with those line heat color decorations:

https://github.com/P403n1x87/austin-vscode/blob/d48825e62cb899d71846ae61d72052b9352187b3/src/view.ts#L46-L62

I'm using a dark theme and if there's a single hottest line, then it becomes kind of unreadable:

![image](https://github.com/P403n1x87/austin-vscode/assets/5229130/9b9f49fb-e0bd-473e-8444-76606b035dde)

You can reproduce it by running the "Profile with Austin" action on this snippet:

```python
import time

time.sleep(5)
```

I tried other dark themes, including the default ones, and the line is more or less hard to read on most of them. While this is somewhat of a corner case, it would probably be nice to fix it regardless. What do you think?

The easiest solution I can think of is just `Math.min(opacity, 0.6)` it. The 60% opacity cap makes it at least (arguably) distinguishable enough:

![image](https://github.com/P403n1x87/austin-vscode/assets/5229130/847fc8aa-4c4b-4a4f-8810-c3dbbf314b8a)

60% is a big share of the time, so, if I understand it correctly, there can't even be more than one such line and it's safe to cap its color. In other words, we're not really missing anything by losing the ability to visually distinguish between lines in 60%-100% own% range :)

What's your thoughts on that?

**Comment by iburakov** [comment]
Just in case you find suggested changes reasonable, here's a PR to save you some time :)

**Comment by P403n1x87** [comment]
@iburakov thanks a lot for looking into this. I have left a comment on the PR 🙂 .
