### ISSUE TITLE
Vscode flamegraph different compared to flamegraph.pl

### ISSUE THREAD

**Issue by andresgit** [P403n1x87/austin-vscode#58]
The flamegraph inside vscode seems wrong to me. In the example below it shows that testcallback function spends most of the time in `__call__` in jit.py, but the flamegraph.pl shows it spends most of the time in multiple `__call__` functions in device.py.

Here is the output of  `austin -o output.txt python3 testtiny.py`:

[output.txt](https://github.com/P403n1x87/austin-vscode/files/13850499/output.txt)

Here is the screenshot of the output.txt file opened in vscode (some of the text is barely readable due to the colors (can this be improved?), but you can find the testcallback function on the image):

![screen](https://github.com/P403n1x87/austin-vscode/assets/9771158/a556fc4c-7a0a-4b71-93d1-844ee6f20e77)

Here is the svg file from `flamegraph.pl output.txt > test.svg`. Note that the testcallback function has a different breakdown compared to the previous image.

![test](https://github.com/P403n1x87/austin-vscode/assets/9771158/e6ecc7da-6af9-47a0-84b3-9b9932dd7498)

**Comment by P403n1x87** [comment]
@andresgit thanks for reporting this. Looking at the attached data, it looks like the visualisation provided by the VS Code extension is the wrong one. I'll try to push a fix out asap.

**Comment by P403n1x87** [comment]
@andresgit the fix will be shipped with release 0.17.1 of the extension
